language: python

python:
  - "3.7.4"

install:
  - pip3 install -r lab1/requirements.txt
  - pip3 install -r lab2/requirements.txt
  - pip3 install -r lab3/requirements.txt
  - pip3 install -r lab4/requirements.txt

script: 
  - python3 -m doctest -v lab1/functionality.py
  - python3 -m doctest -v lab2/functionality.py
  - python3 -m doctest -v lab3/functionality.py
  - python3 -m doctest -v lab4/trws_algorithm.py lab4/gmm_algorithm.py
