language: python

python:
  - "3.7.4"

install:
  - pip3 install -r lab1/requirements.txt
  - pip3 install -r lab2/requirements.txt

script: 
  - python3 -m doctest -v lab1/functionality.py
  - python3 -m doctest -v lab2/functionality.py
